<?php include 'includes/header.php'?>
<h1 >My First PHP</h1>
<p>This is Standard HTML</p>
<!-- This is an html comment:  can be seen in the source code.  -->

<?php
// put your code here
#another single line php comment
/*
 * this is a multi line comment
 */
/**
 * phpDoc comments
 */
echo '<p>This is another paragraph generated by PHP</p>';
?>
<h2>Now Back to HTML</h2>
<p>
    <?php
    print 'We can either use echo or print';

    $fun = "PHP is fun ";
    echo "<p>".$fun."</p>";
    echo $_SERVER['SERVER_SOFTWARE'];
    ?>
<br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</p>
<?
echo 'This will only work if the short_open_tag setting in your php.ini is set to on';
?>
<?php include 'includes/footer.php'?>